import tkinter as tk
import tkinter.messagebox as msg
from tkinter import *
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import numpy as np
import pyautogui as screen
import GaussSeidel as gauss
import LaGrange as lagrange
import string_control as control

##FUNCIONES DEL ARCHIVO
def main():
    generate_graphics()

def generate_graphics():
    #Ventana principal
    window = tk.Tk()
    window.title("Proyecto de unidad - Universidad de las Fuerzas Armadas - ESPE")
    window.resizable(0,0)
    window.iconbitmap("ProyectoP2\\favicon.ico")
    window.wm_iconbitmap("ProyectoP2\\favicon.ico")
    window_width = 800
    window_height = 600
    width_screen, height_screen = screen.size()
    window_pos_width = (width_screen/2) - (window_width/2)
    window_pos_heigth = (height_screen/2) - (window_height/2)
    pos = str(int(window_width)) + "x" + str(int(window_height))+"+"+str(int(window_pos_width)) + "+" + str(int(window_pos_heigth))
    window.geometry(pos)
    window.config(bg='#f9fadc')

    ##Frames
    #Frame Gauss
    Frm_title = tk.Frame(window)
    Frm_title.configure(width=800, height=100, bg='#2B2823')
    Frm_title.place(x=0, y=0)
    Frm_Menu = tk.Frame(window)
    Frm_Menu.configure(width=800, height=25, bg="#205225")
    Frm_Menu.place(x=0, y=100)
    Frm_Principal = tk.Frame(window)
    Frm_Principal.configure(width=800, height=475, bg='#f9fadc')
    Frm_Principal.place(x=0, y=125)
    Frm_Principal_location = Frm_Principal.place_info()
    Frm_Principal.place_forget()
    Frm_MatrizA = tk.Frame(Frm_Principal)
    Frm_MatrizA.configure(width=300, height=280 , bg='#8fa691')
    Frm_MatrizA.place(x=36, y=100)
    Frm_MatrizX = tk.Frame(Frm_Principal)
    Frm_MatrizX.configure(width=50, height=280 , bg='#d4ceaa')
    Frm_MatrizX.place(x=404, y=100)
    Frm_Resultados = tk.Frame(Frm_Principal)
    Frm_Resultados.configure(width=70, height=190, bg='#cc3917')
    Frm_Resultados.place(x=603, y=144)
    Frm_Parametros = tk.Frame(Frm_Principal)
    Frm_Parametros.configure(width=200, height=45, bg="#FFFFFF")
    Frm_Parametros.place(x=540, y=44)
    #Frame Interpolacion
    Frm_Interpolacion = tk.Frame(window)
    Frm_Interpolacion.configure(width=800, height=475, bg='#f9fadc')
    Frm_Interpolacion.place(x=0, y=125)
    Frm_Interpolacion_location = Frm_Interpolacion.place_info()
    Frm_Interpolacion.place_forget()
    Frm_x = tk.Frame(Frm_Interpolacion)
    Frm_x.configure(width=50, height=40, bg="#CC3917")
    Frm_x.place(x=98, y=87)
    Frm_y = tk.Frame(Frm_Interpolacion)
    Frm_y.configure(width=50, height=40, bg="#CC3917")
    Frm_y.place(x=148, y=87)
    Frm_dataX = tk.Frame(Frm_Interpolacion)
    Frm_dataX.configure(width=50, height=190, bg="#8FA691")
    Frm_dataX.place(x=98, y=126)
    Frm_dataY = tk.Frame(Frm_Interpolacion)
    Frm_dataY.configure(width=50, height=190, bg="#8FA691")
    Frm_dataY.place(x=148, y=126)
    Frm_canvas = tk.Frame(Frm_Interpolacion)
    Frm_canvas.configure(width=400, height=400, bg="black")
    Frm_canvas.place(x=316, y=47)

    ##CANVAS
    fig, graph = plt.subplots()
    plt.xlabel("X axis")
    plt.ylabel("Y axis")
    plt.title("Lagrange Interpolation")
    canvas = FigureCanvasTkAgg(fig, master=Frm_canvas)
    canvas.draw()
    canvas.get_tk_widget().configure(width=400, height=400)
    canvas.get_tk_widget().place(x=0, y=0)

    #Matriz de coeficientes
    txt_a11 = tk.Entry(Frm_MatrizA)
    txt_a11.configure(font=("Inter",12), fg="black", bg="white")
    txt_a11.place(x=44, y=28, width=32, height=32)
    txt_a11.focus()
    txt_a12 = tk.Entry(Frm_MatrizA)
    txt_a12.configure(font=("Inter",12), fg="black", bg="white")
    txt_a12.place(x=104, y=28, width=32, height=32)
    txt_a13 = tk.Entry(Frm_MatrizA)
    txt_a13.configure(font=("Inter",12), fg="black", bg="white")
    txt_a13.place(x=164, y=28, width=32, height=32)
    txt_a14 = tk.Entry(Frm_MatrizA)
    txt_a14.configure(font=("Inter",12), fg="black", bg="white")
    txt_a14.place(x=224, y=28, width=32, height=32)
    txt_a21 = tk.Entry(Frm_MatrizA)
    txt_a21.configure(font=("Inter",12), fg="black", bg="white")
    txt_a21.place(x=44, y=88, width=32, height=32)
    txt_a22 = tk.Entry(Frm_MatrizA)
    txt_a22.configure(font=("Inter",12), fg="black", bg="white")
    txt_a22.place(x=104, y=88, width=32, height=32)
    txt_a23 = tk.Entry(Frm_MatrizA)
    txt_a23.configure(font=("Inter",12), fg="black", bg="white")
    txt_a23.place(x=164, y=88, width=32, height=32)
    txt_a24 = tk.Entry(Frm_MatrizA)
    txt_a24.configure(font=("Inter",12), fg="black", bg="white")
    txt_a24.place(x=224, y=88, width=32, height=32)
    txt_a31 = tk.Entry(Frm_MatrizA)
    txt_a31.configure(font=("Inter",12), fg="black", bg="white")
    txt_a31.place(x=44, y=148, width=32, height=32)
    txt_a32 = tk.Entry(Frm_MatrizA)
    txt_a32.configure(font=("Inter",12), fg="black", bg="white")
    txt_a32.place(x=104, y=148, width=32, height=32)
    txt_a33 = tk.Entry(Frm_MatrizA)
    txt_a33.configure(font=("Inter",12), fg="black", bg="white")
    txt_a33.place(x=164, y=148, width=32, height=32)
    txt_a34 = tk.Entry(Frm_MatrizA)
    txt_a34.configure(font=("Inter",12), fg="black", bg="white")
    txt_a34.place(x=224, y=148, width=32, height=32)
    txt_a41 = tk.Entry(Frm_MatrizA)
    txt_a41.configure(font=("Inter",12), fg="black", bg="white")
    txt_a41.place(x=44, y=208, width=32, height=32)
    txt_a42 = tk.Entry(Frm_MatrizA)
    txt_a42.configure(font=("Inter",12), fg="black", bg="white")
    txt_a42.place(x=104, y=208, width=32, height=32)
    txt_a43 = tk.Entry(Frm_MatrizA)
    txt_a43.configure(font=("Inter",12), fg="black", bg="white")
    txt_a43.place(x=164, y=208, width=32, height=32)
    txt_a44 = tk.Entry(Frm_MatrizA)
    txt_a44.configure(font=("Inter",12), fg="black", bg="white")
    txt_a44.place(x=224, y=208, width=32, height=32)
    txt_tolerancia = tk.Entry(Frm_Parametros)
    txt_tolerancia.configure(font=("Inter",10), fg="black", bg="#D9D9D9")
    txt_tolerancia.place(x=148, y=13, width=40, height=20)

    #Terminos independientes
    txt_x1 = tk.Entry(Frm_MatrizX)
    txt_x1.configure(font=("Inter",12), fg="black", bg="white")
    txt_x1.place(x=9, y=28, width=32, height=32)
    txt_x2 = tk.Entry(Frm_MatrizX)
    txt_x2.configure(font=("Inter",12), fg="black", bg="white")
    txt_x2.place(x=9, y=88, width=32, height=32)
    txt_x3 = tk.Entry(Frm_MatrizX)
    txt_x3.configure(font=("Inter",12), fg="black", bg="white")
    txt_x3.place(x=9, y=148, width=32, height=32)
    txt_x4 = tk.Entry(Frm_MatrizX)
    txt_x4.configure(font=("Inter",12), fg="black", bg="white")
    txt_x4.place(x=9, y=208, width=32, height=32)

    #Textbox Interpolacion
    txt_data_X1 = tk.Entry(Frm_dataX)
    txt_data_X1.configure(font=("Inter",8), fg="black", bg="white")
    txt_data_X1.place(x=10, y=18, width=30, height=30)
    txt_data_X2 = tk.Entry(Frm_dataX)
    txt_data_X2.configure(font=("Inter",8), fg="black", bg="white")
    txt_data_X2.place(x=10, y=60, width=30, height=30)
    txt_data_X3 = tk.Entry(Frm_dataX)
    txt_data_X3.configure(font=("Inter",8), fg="black", bg="white")
    txt_data_X3.place(x=10, y=102, width=30, height=30)
    txt_data_X4 = tk.Entry(Frm_dataX)
    txt_data_X4.configure(font=("Inter",8), fg="black", bg="white")
    txt_data_X4.place(x=10, y=144, width=30, height=30)
    txt_data_Y1 = tk.Entry(Frm_dataY)
    txt_data_Y1.configure(font=("Inter",8), fg="black", bg="white")
    txt_data_Y1.place(x=10, y=18, width=30, height=30)
    txt_data_Y2 = tk.Entry(Frm_dataY)
    txt_data_Y2.configure(font=("Inter",8), fg="black", bg="white")
    txt_data_Y2.place(x=10, y=60, width=30, height=30)
    txt_data_Y3 = tk.Entry(Frm_dataY)
    txt_data_Y3.configure(font=("Inter",8), fg="black", bg="white")
    txt_data_Y3.place(x=10, y=102, width=30, height=30)
    txt_data_Y4 = tk.Entry(Frm_dataY)
    txt_data_Y4.configure(font=("Inter",8), fg="black", bg="white")
    txt_data_Y4.place(x=10, y=144, width=30, height=30)
    txt_xn = tk.Entry(Frm_Interpolacion)
    txt_xn.configure(font=("Inter",8), fg="black", bg="white")
    txt_xn.place(x=83, y=337, width=25, height=25)

    #Resultados
    lbl_b1 = tk.Label(Frm_Resultados)
    lbl_b1.configure(font=("Inter",8, "bold"), fg="white", bg="#cc3917", state="disabled")
    lbl_b1.place(x=5, y=15)
    lbl_b2 = tk.Label(Frm_Resultados)
    lbl_b2.configure(font=("Inter",8, "bold"), fg="white", bg="#cc3917", state="disabled")
    lbl_b2.place(x=5, y=61)
    lbl_b3 = tk.Label(Frm_Resultados)
    lbl_b3.configure(font=("Inter",8, "bold"), fg="white", bg="#cc3917", state="disabled")
    lbl_b3.place(x=5, y=106)
    lbl_b4 = tk.Label(Frm_Resultados)
    lbl_b4.configure(font=("Inter",8, "bold"), fg="white", bg="#cc3917", state="disabled")
    lbl_b4.place(x=5, y=152)

    #Labels
    lbl_tittle = tk.Label(Frm_title, bg='#2b2823')
    lbl_tittle.configure(font=("Corinthia",60), text="Métodos Numéricos", fg='white')
    lbl_tittle.place(x=180, y=-10)
    lbl_matrix = tk.Label(Frm_Principal)
    lbl_matrix.configure(text="Matriz de coeficientes 4x4:", font=("Inter",12, "bold"), fg="black", bg='#f9fadc')
    lbl_matrix.place(x=83, y=67)
    lbl_X = tk.Label(Frm_Principal)
    lbl_X.configure(text="X", font=("Inter",12, "bold"), fg="black", bg="#f9fadc")
    lbl_X.place(x=359, y=229)
    lbl_equal = tk.Label(Frm_Principal)
    lbl_equal.configure(text="=", font=("Inter",12, "bold"),fg="black", bg="#f9fadc")
    lbl_equal.place(x=476, y=229)
    lbl_resultado = tk.Label(Frm_Principal)
    lbl_resultado.configure(text="Resultados:", font=("Inter",12, "bold"), fg="black", bg="#f9fadc")
    lbl_resultado.place(x=593, y=100)
    lbl_terminos = tk.Label(Frm_Principal)
    lbl_terminos.configure(text="Términos\nindependientes:", font=("Inter",12, "bold"), fg="black", bg="#f9fadc")
    lbl_terminos.place(x=368, y=44)
    lbl_axb = tk.Label(Frm_Principal)
    lbl_axb.configure(text="A * x = b", font=("Inter",40, "bold"), fg="black", bg="#f9fadc")
    lbl_axb.place(x=317, y=408)
    lbl_parametros = tk.Label(Frm_Principal)
    lbl_parametros.configure(text="Parámetros:",font=("Inter",16, "bold"), fg="black", bg="#F9FADC")
    lbl_parametros.place(x=580, y=10)
    lbl_tolerancia = tk.Label(Frm_Parametros)
    lbl_tolerancia.configure(text="Tolerancia:",font=("Inter",10, "bold"), fg="black", bg="#FFFFFF")
    lbl_tolerancia.place(x=11, y=15)
    lbl_status = tk.Label(Frm_Principal)
    lbl_status.configure(text="Status:", font=("Inter",10, "bold"), fg="black", bg="#F9FADC")
    lbl_status.place(x=487, y=340)
    lbl_status_resultado = tk.Label(Frm_Principal)
    lbl_status_resultado.configure(font=("Inter",10, "bold"), fg="black", bg="#F9FADC")
    lbl_status_resultado.place(x=540, y=340)
    lbl_p4 = tk.Label(Frm_Interpolacion)
    lbl_p4.configure(text="P(4):", font=("Inter",20, "bold"), fg="black", bg="#F9FADC")
    lbl_p4.place(x=316, y=5)
    lbl_modelo = tk.Label(Frm_Interpolacion)
    lbl_modelo.configure(font=("Inter",10, "bold"), fg="black", bg="#F9FADC")
    lbl_modelo.place(x=400, y=15)
    lbl_x = tk.Label(Frm_x)
    lbl_x.configure(text="X",font=("Inter",20, "bold"), fg="white", bg="#CC3917")
    lbl_x.place(x=12, y=3)
    lbl_y = tk.Label(Frm_y)
    lbl_y.configure(text="Y",font=("Inter",20, "bold"), fg="white", bg="#CC3917")
    lbl_y.place(x=12, y=3)
    lbl_xn = tk.Label(Frm_Interpolacion)
    lbl_xn.configure(text="Xn:", font=("Inter",10, "bold"), fg="black", bg="#F9FADC")
    lbl_xn.place(x=47, y=342)
    lbl_resultado_interpolador = tk.Label(Frm_Interpolacion)
    lbl_resultado_interpolador.configure(text="Resultados:", font=("Inter",10, "bold"), fg="black", bg="#F9FADC")   
    lbl_resultado_interpolador.place(x=135, y=342)
    lbl_resultado_xn = tk.Label(Frm_Interpolacion)
    lbl_resultado_xn.configure(font=("Inter",10, "normal"), fg="black", bg="#F9FADC")
    lbl_resultado_xn.place(x=225, y=342)

    #Botones
    btn_Calcular = tk.Button(Frm_Principal)
    btn_Calcular.configure(text="Calcular", font=("Inter",10, "bold"), fg="white", bg='#2b2823')
    btn_Calcular.place(x=592, y=383, width=100, height=30)
    btn_Limpiar = tk.Button(Frm_Principal)
    btn_Limpiar.configure(text="Limpiar", font=("Inter",10, "bold"), fg="white", bg='#2b2823')
    btn_Limpiar.place(x=604, y=422, width=75, height=25)
    btn_Gauss = tk.Button(Frm_Menu)
    btn_Gauss.configure(text="Gauss-Seidel", font=("Inter",10, "bold"), fg="white", bg='#205225', relief="ridge", bd=1)
    btn_Gauss.place(x=0, y=0, width=125, height=25)
    btn_Interpolacion = tk.Button(Frm_Menu)
    btn_Interpolacion.configure(text="Interpolacion", font=("Inter",10, "bold"), fg="white", bg='#205225', relief="ridge", bd=1)
    btn_Interpolacion.place(x=125, y=0, width=125, height=25)
    btn_Caso1 = tk.Button(Frm_Principal)
    btn_Caso1.configure(text="Caso 1", font=("Inter",10, "bold"), fg="white", bg='#2b2823')
    btn_Caso1.place(x=13, y=12, width=67, height=23)
    btn_Caso2 = tk.Button(Frm_Principal)
    btn_Caso2.configure(text="Caso 2", font=("Inter",10, "bold"), fg="white", bg='#2b2823')
    btn_Caso2.place(x=89, y=12, width=67, height=23)
    btn_Caso3 = tk.Button(Frm_Principal)
    btn_Caso3.configure(text="Caso 3", font=("Inter",10, "bold"), fg="white", bg='#2b2823')
    btn_Caso3.place(x=165, y=12, width=67, height=23)
    btn_Caso4 = tk.Button(Frm_Principal)
    btn_Caso4.configure(text="Caso 4", font=("Inter",10, "bold"), fg="white", bg='#2b2823')
    btn_Caso4.place(x=241, y=12, width=67, height=23)
    btn_Caso1_Interpolacion = tk.Button(Frm_Interpolacion)
    btn_Caso1_Interpolacion.configure(text="Caso 1", font=("Inter",10, "bold"), fg="white", bg='#2b2823')
    btn_Caso1_Interpolacion.place(x=13, y=12, width=67, height=23)
    btn_Caso2_Interpolacion = tk.Button(Frm_Interpolacion)
    btn_Caso2_Interpolacion.configure(text="Caso 2", font=("Inter",10, "bold"), fg="white", bg='#2b2823')
    btn_Caso2_Interpolacion.place(x=89, y=12, width=67, height=23)
    btn_Calcular_interpolacion = tk.Button(Frm_Interpolacion)
    btn_Calcular_interpolacion.configure(text="Calcular", font=("Inter",15, "bold"), fg="white", bg='#2b2823')
    btn_Calcular_interpolacion.place(x=98, y=377, width=100, height=30)
    btn_Reset_interpolacion = tk.Button(Frm_Interpolacion)
    btn_Reset_interpolacion.configure(text="Reset", font=("Inter",12, "bold"), fg="white", bg='#2b2823')
    btn_Reset_interpolacion.place(x=110, y=422, width=75, height=25)

    #Iniciar funcionalidades
    A_caso1 = gauss.A_caso1
    b_caso1 = gauss.b_caso1
    A_caso2 = gauss.A_caso2
    b_caso2 = gauss.b_caso2
    A_caso3 = gauss.A_caso3
    b_caso3 = gauss.b_caso3
    A_caso4 = gauss.A_caso4
    b_caso4 = gauss.b_caso4

    tolerancia = 0.000001
    txt_tolerancia.insert(0,str(tolerancia))
    zero_matrix =np.zeros(4)

    #Acciones botones
    def btn_gauss_clic_event(event):
        Frm_Interpolacion.place_forget()
        Frm_Principal.place(Frm_Principal_location)
        return
    def btn_interpolacion_clic_event(event):
        Frm_Principal.place_forget()
        Frm_Interpolacion.place(Frm_Interpolacion_location)
        return
    def calcular_clic_event(event):
        try:
            a11 = float(txt_a11.get())
            a12 = float(txt_a12.get())
            a13 = float(txt_a13.get())
            a14 = float(txt_a14.get())
            a21 = float(txt_a21.get())
            a22 = float(txt_a22.get())
            a23 = float(txt_a23.get())
            a24 = float(txt_a24.get())
            a31 = float(txt_a31.get())
            a32 = float(txt_a32.get())
            a33 = float(txt_a33.get())
            a34 = float(txt_a34.get())
            a41 = float(txt_a41.get())
            a42 = float(txt_a42.get())
            a43 = float(txt_a43.get())
            a44 = float(txt_a44.get())
            x1 = float(txt_x1.get())
            x2 = float(txt_x2.get())
            x3 = float(txt_x3.get())
            x4 = float(txt_x4.get())
            tolerancia = float(txt_tolerancia.get())
            A = np.array([
                [a11, a12, a13, a14],
                [a21, a22, a23, a24],
                [a31, a32, a33, a34],
                [a41, a42, a43, a44]])
            x = np.array([x1, x2, x3, x4])
            matrix_comprobation, status, iter = gauss.matrix_validate(A, x)
            if(matrix_comprobation == True):
                b, iter = gauss.gauss_seidel(A, x, zero_matrix, tolerancia)
            mood = StringVar()
            aux_status = status + "\n Con ", iter , " iteraciones"
            mood.set(aux_status)
            if status == "Sistema válido":
                lbl_b1.configure(text=str(round(b[0],7)), state="normal")
                lbl_b2.configure(text=str(round(b[1],7)), state="normal")
                lbl_b3.configure(text=str(round(b[2],7)), state="normal")
                lbl_b4.configure(text=str(round(b[3],7)), state="normal")
                lbl_status_resultado.configure(textvariable=mood)
            else:
                lbl_b1.configure(text="N/A", state="normal")
                lbl_b2.configure(text="N/A", state="normal")
                lbl_b3.configure(text="N/A", state="normal")
                lbl_b4.configure(text="N/A", state="normal")
                lbl_status_resultado.configure(textvariable=mood)
                msg.showinfo("Estado de resultados", status)
        except Exception as e:
            msg.showerror("Error", f"Error: {e.args[0]}")
            return
    def limpiar_clic_event(event):
        try:
            void_string = StringVar()
            void_string.set("")
            txt_a11.configure(textvariable=void_string)
            txt_a11.focus()
            txt_a12.configure(textvariable=void_string)
            txt_a13.configure(textvariable=void_string)
            txt_a14.configure(textvariable=void_string)
            txt_a21.configure(textvariable=void_string)
            txt_a22.configure(textvariable=void_string)
            txt_a23.configure(textvariable=void_string)
            txt_a24.configure(textvariable=void_string)
            txt_a31.configure(textvariable=void_string)
            txt_a32.configure(textvariable=void_string)
            txt_a33.configure(textvariable=void_string)
            txt_a34.configure(textvariable=void_string)
            txt_a41.configure(textvariable=void_string)
            txt_a42.configure(textvariable=void_string)
            txt_a43.configure(textvariable=void_string)
            txt_a44.configure(textvariable=void_string)
            txt_x1.configure(textvariable=void_string)
            txt_x2.configure(textvariable=void_string)
            txt_x3.configure(textvariable=void_string)
            txt_x4.configure(textvariable=void_string)
            lbl_b1.configure(textvariable=void_string, state="disabled")
            lbl_b2.configure(textvariable=void_string, state="disabled")
            lbl_b3.configure(textvariable=void_string, state="disabled")
            lbl_b4.configure(textvariable=void_string, state="disabled")
        except Exception as e:
            msg.showerror("Error", f"Error: {e.args[0]}")
            return
    def caso1_clic_event(event):
        try:
            a11_string = StringVar()
            a11_string.set(str(A_caso1[0][0]))
            a12_string = StringVar()
            a12_string.set(str(A_caso1[0][1]))
            a13_string = StringVar()
            a13_string.set(str(A_caso1[0][2]))
            a14_string = StringVar()
            a14_string.set(str(A_caso1[0][3]))
            a21_string = StringVar()
            a21_string.set(str(A_caso1[1][0]))
            a22_string = StringVar()
            a22_string.set(str(A_caso1[1][1]))
            a23_string = StringVar()
            a23_string.set(str(A_caso1[1][2]))
            a24_string = StringVar()
            a24_string.set(str(A_caso1[1][3]))
            a31_string = StringVar()
            a31_string.set(str(A_caso1[2][0]))
            a32_string = StringVar()
            a32_string.set(str(A_caso1[2][1]))
            a33_string = StringVar()
            a33_string.set(str(A_caso1[2][2]))
            a34_string = StringVar()
            a34_string.set(str(A_caso1[2][3]))
            a41_string = StringVar()
            a41_string.set(str(A_caso1[3][0]))
            a42_string = StringVar()
            a42_string.set(str(A_caso1[3][1]))
            a43_string = StringVar()
            a43_string.set(str(A_caso1[3][2]))
            a44_string = StringVar()
            a44_string.set(str(A_caso1[3][3]))
            x1_string = StringVar()
            x1_string.set(str(b_caso1[0]))
            x2_string = StringVar()
            x2_string.set(str(b_caso1[1]))
            x3_string = StringVar()
            x3_string.set(str(b_caso1[2]))
            x4_string = StringVar()
            x4_string.set(str(b_caso1[3]))
            txt_a11.configure(textvariable=a11_string)
            txt_a12.configure(textvariable=a12_string)
            txt_a13.configure(textvariable=a13_string)
            txt_a14.configure(textvariable=a14_string)
            txt_a21.configure(textvariable=a21_string)
            txt_a22.configure(textvariable=a22_string)
            txt_a23.configure(textvariable=a23_string)
            txt_a24.configure(textvariable=a24_string)
            txt_a31.configure(textvariable=a31_string)
            txt_a32.configure(textvariable=a32_string)
            txt_a33.configure(textvariable=a33_string)
            txt_a34.configure(textvariable=a34_string)
            txt_a41.configure(textvariable=a41_string)
            txt_a42.configure(textvariable=a42_string)
            txt_a43.configure(textvariable=a43_string)
            txt_a44.configure(textvariable=a44_string)
            txt_x1.configure(textvariable=x1_string)
            txt_x2.configure(textvariable=x2_string)
            txt_x3.configure(textvariable=x3_string)
            txt_x4.configure(textvariable=x4_string)
        except Exception as e:
            msg.showerror("Error", f"Error: {e.args[0]}")
            return
    def caso2_clic_event(event):
        try:
            a11_string = StringVar()
            a11_string.set(str(A_caso2[0][0]))
            a12_string = StringVar()
            a12_string.set(str(A_caso2[0][1]))
            a13_string = StringVar()
            a13_string.set(str(A_caso2[0][2]))
            a14_string = StringVar()
            a14_string.set(str(A_caso2[0][3]))
            a21_string = StringVar()
            a21_string.set(str(A_caso2[1][0]))
            a22_string = StringVar()
            a22_string.set(str(A_caso2[1][1]))
            a23_string = StringVar()
            a23_string.set(str(A_caso2[1][2]))
            a24_string = StringVar()
            a24_string.set(str(A_caso2[1][3]))
            a31_string = StringVar()
            a31_string.set(str(A_caso2[2][0]))
            a32_string = StringVar()
            a32_string.set(str(A_caso2[2][1]))
            a33_string = StringVar()
            a33_string.set(str(A_caso2[2][2]))
            a34_string = StringVar()
            a34_string.set(str(A_caso2[2][3]))
            a41_string = StringVar()
            a41_string.set(str(A_caso2[3][0]))
            a42_string = StringVar()
            a42_string.set(str(A_caso2[3][1]))
            a43_string = StringVar()
            a43_string.set(str(A_caso2[3][2]))
            a44_string = StringVar()
            a44_string.set(str(A_caso2[3][3]))
            x1_string = StringVar()
            x1_string.set(str(b_caso2[0]))
            x2_string = StringVar()
            x2_string.set(str(b_caso2[1]))
            x3_string = StringVar()
            x3_string.set(str(b_caso2[2]))
            x4_string = StringVar()
            x4_string.set(str(b_caso2[3]))
            txt_a11.configure(textvariable=a11_string)
            txt_a12.configure(textvariable=a12_string)
            txt_a13.configure(textvariable=a13_string)
            txt_a14.configure(textvariable=a14_string)
            txt_a21.configure(textvariable=a21_string)
            txt_a22.configure(textvariable=a22_string)
            txt_a23.configure(textvariable=a23_string)
            txt_a24.configure(textvariable=a24_string)
            txt_a31.configure(textvariable=a31_string)
            txt_a32.configure(textvariable=a32_string)
            txt_a33.configure(textvariable=a33_string)
            txt_a34.configure(textvariable=a34_string)
            txt_a41.configure(textvariable=a41_string)
            txt_a42.configure(textvariable=a42_string)
            txt_a43.configure(textvariable=a43_string)
            txt_a44.configure(textvariable=a44_string)
            txt_x1.configure(textvariable=x1_string)
            txt_x2.configure(textvariable=x2_string)
            txt_x3.configure(textvariable=x3_string)
            txt_x4.configure(textvariable=x4_string)
        except Exception as e:
            msg.showerror("Error", f"Error: {e.args[0]}")
            return
    def caso3_clic_event(event):
        try:
            a11_string = StringVar()
            a11_string.set(str(A_caso3[0][0]))
            a12_string = StringVar()
            a12_string.set(str(A_caso3[0][1]))
            a13_string = StringVar()
            a13_string.set(str(A_caso3[0][2]))
            a14_string = StringVar()
            a14_string.set(str(A_caso3[0][3]))
            a21_string = StringVar()
            a21_string.set(str(A_caso3[1][0]))
            a22_string = StringVar()
            a22_string.set(str(A_caso3[1][1]))
            a23_string = StringVar()
            a23_string.set(str(A_caso3[1][2]))
            a24_string = StringVar()
            a24_string.set(str(A_caso3[1][3]))
            a31_string = StringVar()
            a31_string.set(str(A_caso3[2][0]))
            a32_string = StringVar()
            a32_string.set(str(A_caso3[2][1]))
            a33_string = StringVar()
            a33_string.set(str(A_caso3[2][2]))
            a34_string = StringVar()
            a34_string.set(str(A_caso3[2][3]))
            a41_string = StringVar()
            a41_string.set(str(A_caso3[3][0]))
            a42_string = StringVar()
            a42_string.set(str(A_caso3[3][1]))
            a43_string = StringVar()
            a43_string.set(str(A_caso3[3][2]))
            a44_string = StringVar()
            a44_string.set(str(A_caso3[3][3]))
            x1_string = StringVar()
            x1_string.set(str(b_caso3[0]))
            x2_string = StringVar()
            x2_string.set(str(b_caso3[1]))
            x3_string = StringVar()
            x3_string.set(str(b_caso3[2]))
            x4_string = StringVar()
            x4_string.set(str(b_caso3[3]))
            txt_a11.configure(textvariable=a11_string)
            txt_a12.configure(textvariable=a12_string)
            txt_a13.configure(textvariable=a13_string)
            txt_a14.configure(textvariable=a14_string)
            txt_a21.configure(textvariable=a21_string)
            txt_a22.configure(textvariable=a22_string)
            txt_a23.configure(textvariable=a23_string)
            txt_a24.configure(textvariable=a24_string)
            txt_a31.configure(textvariable=a31_string)
            txt_a32.configure(textvariable=a32_string)
            txt_a33.configure(textvariable=a33_string)
            txt_a34.configure(textvariable=a34_string)
            txt_a41.configure(textvariable=a41_string)
            txt_a42.configure(textvariable=a42_string)
            txt_a43.configure(textvariable=a43_string)
            txt_a44.configure(textvariable=a44_string)
            txt_x1.configure(textvariable=x1_string)
            txt_x2.configure(textvariable=x2_string)
            txt_x3.configure(textvariable=x3_string)
            txt_x4.configure(textvariable=x4_string)
        except Exception as e:
            msg.showerror("Error", f"Error: {e.args[0]}")
            return
    def caso4_clic_event(event):
        try:
            a11_string = StringVar()
            a11_string.set(str(A_caso4[0][0]))
            a12_string = StringVar()
            a12_string.set(str(A_caso4[0][1]))
            a13_string = StringVar()
            a13_string.set(str(A_caso4[0][2]))
            a14_string = StringVar()
            a14_string.set(str(A_caso4[0][3]))
            a21_string = StringVar()
            a21_string.set(str(A_caso4[1][0]))
            a22_string = StringVar()
            a22_string.set(str(A_caso4[1][1]))
            a23_string = StringVar()
            a23_string.set(str(A_caso4[1][2]))
            a24_string = StringVar()
            a24_string.set(str(A_caso4[1][3]))
            a31_string = StringVar()
            a31_string.set(str(A_caso4[2][0]))
            a32_string = StringVar()
            a32_string.set(str(A_caso4[2][1]))
            a33_string = StringVar()
            a33_string.set(str(A_caso4[2][2]))
            a34_string = StringVar()
            a34_string.set(str(A_caso4[2][3]))
            a41_string = StringVar()
            a41_string.set(str(A_caso4[3][0]))
            a42_string = StringVar()
            a42_string.set(str(A_caso4[3][1]))
            a43_string = StringVar()
            a43_string.set(str(A_caso4[3][2]))
            a44_string = StringVar()
            a44_string.set(str(A_caso4[3][3]))
            x1_string = StringVar()
            x1_string.set(str(b_caso4[0]))
            x2_string = StringVar()
            x2_string.set(str(b_caso4[1]))
            x3_string = StringVar()
            x3_string.set(str(b_caso4[2]))
            x4_string = StringVar()
            x4_string.set(str(b_caso4[3]))
            txt_a11.configure(textvariable=a11_string)
            txt_a12.configure(textvariable=a12_string)
            txt_a13.configure(textvariable=a13_string)
            txt_a14.configure(textvariable=a14_string)
            txt_a21.configure(textvariable=a21_string)
            txt_a22.configure(textvariable=a22_string)
            txt_a23.configure(textvariable=a23_string)
            txt_a24.configure(textvariable=a24_string)
            txt_a31.configure(textvariable=a31_string)
            txt_a32.configure(textvariable=a32_string)
            txt_a33.configure(textvariable=a33_string)
            txt_a34.configure(textvariable=a34_string)
            txt_a41.configure(textvariable=a41_string)
            txt_a42.configure(textvariable=a42_string)
            txt_a43.configure(textvariable=a43_string)
            txt_a44.configure(textvariable=a44_string)
            txt_x1.configure(textvariable=x1_string)
            txt_x2.configure(textvariable=x2_string)
            txt_x3.configure(textvariable=x3_string)
            txt_x4.configure(textvariable=x4_string)
        except Exception as e:
            msg.showerror("Error", f"Error: {e.args[0]}")
            return
    
    def btn_caso1_interpolacion_clic_event(event):
        try:
            x_points = lagrange.points_caso1
            y_values = lagrange.values_caso1
            x1_string = StringVar()
            x1_string.set(str(x_points[0]))
            x2_string = StringVar()
            x2_string.set(str(x_points[1]))
            x3_string = StringVar()
            x3_string.set(str(x_points[2]))
            x4_string = StringVar()
            x4_string.set(str(x_points[3]))
            txt_data_X1.configure(textvariable=x1_string)
            txt_data_X2.configure(textvariable=x2_string)
            txt_data_X3.configure(textvariable=x3_string)
            txt_data_X4.configure(textvariable=x4_string)
            y1_string = StringVar()
            y1_string.set(str(y_values[0]))
            y2_string = StringVar()
            y2_string.set(str(y_values[1]))
            y3_string = StringVar()
            y3_string.set(str(y_values[2]))
            y4_string = StringVar()
            y4_string.set(str(y_values[3]))
            txt_data_Y1.configure(textvariable=y1_string)
            txt_data_Y2.configure(textvariable=y2_string)
            txt_data_Y3.configure(textvariable=y3_string)
            txt_data_Y4.configure(textvariable=y4_string)
            txt_xn.focus()
        except Exception as e:
            msg.showerror("Error", f"Error: {e.args[0]}")
            return
    def btn_caso2_interpolacion_clic_event(event):
        try:
            x_points = lagrange.points_caso2
            y_values = lagrange.values_caso2
            x1_string = StringVar()
            x1_string.set(str(x_points[0]))
            x2_string = StringVar()
            x2_string.set(str(x_points[1]))
            x3_string = StringVar()
            x3_string.set(str(x_points[2]))
            x4_string = StringVar()
            x4_string.set(str(x_points[3]))
            txt_data_X1.configure(textvariable=x1_string)
            txt_data_X2.configure(textvariable=x2_string)
            txt_data_X3.configure(textvariable=x3_string)
            txt_data_X4.configure(textvariable=x4_string)
            y1_string = StringVar()
            y1_string.set(str(y_values[0]))
            y2_string = StringVar()
            y2_string.set(str(y_values[1]))
            y3_string = StringVar()
            y3_string.set(str(y_values[2]))
            y4_string = StringVar()
            y4_string.set(str(y_values[3]))
            txt_data_Y1.configure(textvariable=y1_string)
            txt_data_Y2.configure(textvariable=y2_string)
            txt_data_Y3.configure(textvariable=y3_string)
            txt_data_Y4.configure(textvariable=y4_string)
            txt_xn.focus()
        except Exception as e:
            msg.showerror("Error", f"Error: {e.args[0]}")
            return
    def btn_calcular_interpolacion_clic_event(event):
        try:
            data_x1=float(txt_data_X1.get())
            data_x2=float(txt_data_X2.get())
            data_x3=float(txt_data_X3.get())
            data_x4=float(txt_data_X4.get())
            data_y1=float(txt_data_Y1.get())
            data_y2=float(txt_data_Y2.get())
            data_y3=float(txt_data_Y3.get())
            data_y4=float(txt_data_Y4.get())
            xn=float(txt_xn.get())
            x_values = [data_x1, data_x2, data_x3, data_x4]
            y_values = [data_y1, data_y2, data_y3, data_y4]
            Px, P = lagrange.Lagrange_interpolation(x_values, y_values, xn)
            respuesta_xn = StringVar()
            respuesta_xn.set(str(round(Px, 6)))
            lbl_resultado_xn.configure(textvariable=respuesta_xn)
            respuesta_P = StringVar()
            respuesta_P.set(str(P))
            lbl_modelo.configure(textvariable=respuesta_P, state="normal")
            x = x_values + [xn]
            y = y_values + [Px]
            max_x = max(x)
            min_x = min(x)
            max_y = max(y)
            min_y = min(y)
            plt.scatter(x, y, color='red', s=50, marker='x')
            """""
            P = P.replace("^", "**")
            if(control.check_syntax(P)):
                f = lambda x: eval(P)
                x = np.linspace(-10, 10, num=1000)
                y = f(x)
                plt.plot(x, y)
                plt.autoscale()
            """
            canvas.draw()
        except Exception as e:
            msg.showerror("Error", f"Error: {e.args[0]}")
            return
    def btn_reset_interpolacion_clic_event(event):
        try:
            void_string = StringVar()
            void_string.set("")
            txt_data_X1.configure(textvariable=void_string)
            txt_data_X1.focus()
            txt_data_X2.configure(textvariable=void_string)
            txt_data_X3.configure(textvariable=void_string)
            txt_data_X4.configure(textvariable=void_string)
            txt_data_Y1.configure(textvariable=void_string)
            txt_data_Y2.configure(textvariable=void_string)
            txt_data_Y3.configure(textvariable=void_string)
            txt_data_Y4.configure(textvariable=void_string)
            txt_xn.configure(textvariable=void_string)
            lbl_modelo.configure(textvariable=void_string, state="disabled")
        except Exception as e:
            msg.showerror("Error", f"Error: {e.args[0]}")
            return
    ##Llamado botones
    btn_Calcular.bind('<Button-1>', calcular_clic_event)
    btn_Limpiar.bind('<Button-1>', limpiar_clic_event)
    btn_Caso1.bind('<Button-1>', caso1_clic_event)
    btn_Caso2.bind('<Button-1>', caso2_clic_event)
    btn_Caso3.bind('<Button-1>', caso3_clic_event)
    btn_Caso4.bind('<Button-1>', caso4_clic_event)
    btn_Gauss.bind('<Button-1>', btn_gauss_clic_event)
    btn_Interpolacion.bind('<Button-1>', btn_interpolacion_clic_event)
    btn_Caso1_Interpolacion.bind('<Button-1>', btn_caso1_interpolacion_clic_event)
    btn_Caso2_Interpolacion.bind('<Button-1>', btn_caso2_interpolacion_clic_event)
    btn_Calcular_interpolacion.bind('<Button-1>', btn_calcular_interpolacion_clic_event)
    btn_Reset_interpolacion.bind('<Button-1>', btn_reset_interpolacion_clic_event)

    window.mainloop()

##MAIN
main()